### PR TITLE
Remove some duplication

### PR DESCRIPTION
**Pull request by errm**
The code is not very DRY, as all the functions can be composed from `ternary`

### CODE REVIEW

**Comment by derhuerst** [comment]
I thought about this as well. Would be interested in the performance compared to what it is right now. Will set up a `benchmark` script.

**Comment by derhuerst** [comment]
On `master`:

```
curried with 0 args x 49,103,871 ops/sec ±0.72% (85 runs sampled)
curried with 1 arg x 48,772,097 ops/sec ±0.81% (85 runs sampled)
curried with 2 args x 34,525,863 ops/sec ±0.42% (83 runs sampled)
called with 3 args x 13,202,579 ops/sec ±0.52% (85 runs sampled)
```

On `errm/dedupe`:

```
curried with 0 args x 35,212,293 ops/sec ±0.70% (86 runs sampled)
curried with 1 arg x 35,462,651 ops/sec ±0.58% (84 runs sampled)
curried with 2 args x 27,266,310 ops/sec ±0.65% (91 runs sampled)
called with 3 args x 13,277,275 ops/sec ±0.20% (88 runs sampled)
```

In my opinion, it is really a matter of taste if the DRYer code is worth a 40% slowdown.

**Comment by derhuerst** [comment]
What do you think?

**Comment by derhuerst** [comment]
ping

**Comment by errm** [comment]
If there are use-cases for the library that would cause bottlenecks to occur here then perhaps optimise for speed.  

Otherwise it seems fast enough in either case, I would go for the cleaner code.

**Comment by errm** [comment]
:)

**Pull request merged**
